# Generated by Django 4.2.1 on 2023-06-22 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0003_facility_bus_facilities"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={"verbose_name_plural": "facilities"},
        ),
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="station.order",
            ),
        ),
    ]
