# Generated by Django 4.2.1 on 2023-06-22 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0004_alter_facility_options_alter_ticket_order"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ticket",
            name="unique_ticket_seat_trip",
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(max_length=63, unique=True),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="trip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="station.trip",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together={("seat", "trip")},
        ),
    ]
