# Generated by Django 4.2.1 on 2023-06-22 10:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0005_remove_ticket_unique_ticket_seat_trip_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["seat"]},
        ),
    ]
