# Generated by Django 4.2.1 on 2023-06-25 06:24

from django.db import migrations, models
import station.models


class Migration(migrations.Migration):
    dependencies = [
        ("station", "0006_alter_ticket_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bus",
            name="image",
            field=models.ImageField(
                null=True, upload_to=station.models.bus_image_file_path
            ),
        ),
    ]
